replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  - name: JAVA_HOME
    value: "/usr/lib/jvm/default-java"
  - name: DATA_PATH
    value: "/app/data/train.parquet"

volumeMounts:
  - mountPath: "/app/data"
    name: spark-data-volume

volumes:
  - name: spark-data-volume
    hostPath:
      path: "/mnt/data"  # مسیر داده‌ها در هاست
      type: Directory

